/**
 * PhantomMindAI — CLI Init Command
 * Interactive project initialization.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { PhantomConfig, AdapterName, ProviderName } from '../types.js';
import { getDefaultConfig } from '../config/loader.js';

export interface InitOptions {
  adapters?: string[];
  provider?: string;
  model?: string;
  yes?: boolean;
  interactive?: boolean;
}

export async function initCommand(
  projectRoot: string,
  options: InitOptions,
): Promise<void> {
  const chalk = (await import('chalk')).default;
  const ora = (await import('ora')).default;

  console.log(chalk.bold.cyan('\n🔮 PhantomMindAI — Project Initialization\n'));

  const spinner = ora('Setting up PhantomMindAI...').start();

  try {
    // Create .phantomind directory
    const phantomDir = join(projectRoot, '.phantomind');
    const dirs = [
      phantomDir,
      join(phantomDir, 'memory'),
      join(phantomDir, 'cache'),
      join(phantomDir, 'audit'),
      join(phantomDir, 'schemas'),
    ];

    for (const dir of dirs) {
      if (!existsSync(dir)) {
        await mkdir(dir, { recursive: true });
      }
    }

    spinner.text = 'Generating configuration...';

    // Build config
    const config: PhantomConfig = {
      ...getDefaultConfig(),
    };

    if (options.provider) {
      config.providers = {
        ...config.providers,
        primary: {
          ...config.providers.primary,
          name: options.provider as ProviderName,
        },
      };
    }

    if (options.model) {
      config.providers = {
        ...config.providers,
        primary: {
          ...config.providers.primary,
          model: options.model,
        },
      };
    }

    if (options.adapters) {
      config.adapters = options.adapters as AdapterName[];
    }

    // Write config file
    const configPath = join(projectRoot, 'phantomind.config.json');
    if (!existsSync(configPath)) {
      await writeFile(configPath, JSON.stringify(config, null, 2));
      spinner.succeed('Created phantomind.config.json');
    } else {
      spinner.info('phantomind.config.json already exists, skipping');
    }

    // Create SKILLS.md
    const skillsPath = join(phantomDir, 'SKILLS.md');
    if (!existsSync(skillsPath)) {
      const skillsContent = [
        `# ${detectProjectName(projectRoot)} — AI Skills & Context`,
        '',
        '> Auto-generated by PhantomMindAI. Customize to improve AI assistance.',
        '',
        '## Project Overview',
        `- **Root**: ${projectRoot}`,
        `- **Initialized**: ${new Date().toISOString()}`,
        '',
        '## Tech Stack',
        '<!-- Add your tech stack here -->',
        '',
        '## Coding Conventions',
        '<!-- Add your conventions here -->',
        '',
        '## Key Files',
        '<!-- Add important files here -->',
        '',
      ].join('\n');
      await writeFile(skillsPath, skillsContent);
    }

    // Create RULES.md
    const rulesPath = join(phantomDir, 'RULES.md');
    if (!existsSync(rulesPath)) {
      const rulesContent = [
        `# ${detectProjectName(projectRoot)} — AI Rules`,
        '',
        '> Auto-generated by PhantomMindAI. Customize to set boundaries.',
        '',
        '## General Rules',
        '1. Follow the existing code style',
        '2. Never hardcode secrets or credentials',
        '3. Always handle errors appropriately',
        '4. Write self-documenting code',
        '5. Keep functions focused and small',
        '',
        '## Forbidden Patterns',
        '- Do not use `any` type in TypeScript',
        '- Do not use `console.log` for production logging',
        '- Do not commit commented-out code',
        '',
      ].join('\n');
      await writeFile(rulesPath, rulesContent);
    }

    // Create .env.example
    const envExamplePath = join(projectRoot, '.env.phantomind.example');
    if (!existsSync(envExamplePath)) {
      const envContent = [
        '# PhantomMindAI Environment Variables',
        '# Copy to .env.phantomind and fill in your values',
        '',
        '# Provider API Keys (set the ones you need)',
        'ANTHROPIC_API_KEY=',
        'OPENAI_API_KEY=',
        'GOOGLE_API_KEY=',
        'GROQ_API_KEY=',
        'MISTRAL_API_KEY=',
        'DEEPSEEK_API_KEY=',
        'OPENROUTER_API_KEY=',
        '',
        '# Optional: Ollama (local models)',
        '# OLLAMA_HOST=http://localhost:11434',
        '',
      ].join('\n');
      await writeFile(envExamplePath, envContent);
    }

    console.log('');
    console.log(chalk.green('✅ PhantomMindAI initialized successfully!'));
    console.log('');
    console.log(chalk.dim('Next steps:'));
    console.log(chalk.dim(`  1. Copy ${chalk.white('.env.phantomind.example')} to ${chalk.white('.env.phantomind')} and add your API keys`));
    console.log(chalk.dim(`  2. Customize ${chalk.white('.phantomind/SKILLS.md')} with your project context`));
    console.log(chalk.dim(`  3. Run ${chalk.white('phantomind sync')} to generate adapter configs`));
    console.log(chalk.dim(`  4. Run ${chalk.white('phantomind serve')} to start the MCP server`));
    console.log('');
  } catch (error) {
    spinner.fail('Initialization failed');
    throw error;
  }
}

function detectProjectName(root: string): string {
  try {
    const pkg = require(join(root, 'package.json'));
    return pkg.name ?? root.split('/').pop() ?? 'project';
  } catch {
    return root.split('/').pop() ?? 'project';
  }
}
