/**
 * PhantomMindAI — Incremental Context Learner
 * Passively observes developer patterns and auto-generates SKILLS.md entries.
 */

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import fastGlob from 'fast-glob';

interface LearnedPattern {
  type: 'naming' | 'structure' | 'import' | 'architecture' | 'convention';
  pattern: string;
  confidence: number;
  examples: string[];
  firstSeen: string;
  lastSeen: string;
  occurrences: number;
}

interface LearningState {
  patterns: LearnedPattern[];
  fileHistory: Array<{ path: string; timestamp: string }>;
  lastScanTimestamp: string;
}

export class ContextLearner {
  private projectRoot: string;
  private state: LearningState;
  private statePath: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.statePath = join(projectRoot, '.phantomind', 'memory', 'learning-state.json');
    this.state = { patterns: [], fileHistory: [], lastScanTimestamp: '' };
  }

  /**
   * Load persisted learning state
   */
  async load(): Promise<void> {
    try {
      const raw = await readFile(this.statePath, 'utf-8');
      this.state = JSON.parse(raw);
    } catch {
      // Fresh state
    }
  }

  /**
   * Scan project and learn patterns
   */
  async learn(): Promise<LearnedPattern[]> {
    await this.load();

    const files = await fastGlob('**/*.{ts,tsx,js,jsx,swift,go,py,rs,java,kt}', {
      cwd: this.projectRoot,
      ignore: ['node_modules/**', 'dist/**', 'build/**', '.git/**'],
    });

    const namingPatterns: Map<string, number> = new Map();
    const importPatterns: Map<string, number> = new Map();
    const structurePatterns: Map<string, string[]> = new Map();

    for (const file of files) {
      try {
        const content = await readFile(join(this.projectRoot, file), 'utf-8');
        const ext = extname(file);

        // Detect naming conventions
        this.detectNamingPatterns(content, ext, namingPatterns);

        // Detect import patterns
        this.detectImportPatterns(content, ext, importPatterns);

        // Detect architecture patterns
        this.detectStructurePatterns(file, structurePatterns);
      } catch {
        continue;
      }
    }

    // Convert to learned patterns
    const newPatterns: LearnedPattern[] = [];
    const now = new Date().toISOString();

    for (const [pattern, count] of namingPatterns) {
      if (count >= 3) {
        newPatterns.push({
          type: 'naming',
          pattern,
          confidence: Math.min(count / 10, 1.0),
          examples: [],
          firstSeen: now,
          lastSeen: now,
          occurrences: count,
        });
      }
    }

    for (const [pattern, count] of importPatterns) {
      if (count >= 2) {
        newPatterns.push({
          type: 'import',
          pattern,
          confidence: Math.min(count / 5, 1.0),
          examples: [],
          firstSeen: now,
          lastSeen: now,
          occurrences: count,
        });
      }
    }

    for (const [pattern, examples] of structurePatterns) {
      if (examples.length >= 2) {
        newPatterns.push({
          type: 'structure',
          pattern,
          confidence: Math.min(examples.length / 5, 1.0),
          examples: examples.slice(0, 5),
          firstSeen: now,
          lastSeen: now,
          occurrences: examples.length,
        });
      }
    }

    // Merge with existing patterns
    this.mergePatterns(newPatterns);
    this.state.lastScanTimestamp = now;
    await this.save();

    return this.state.patterns;
  }

  /**
   * Generate SKILLS.md content from learned patterns
   */
  generateSkillsContent(): string {
    const lines = [
      '# Project Skills (Auto-learned)',
      '',
      '> This file was auto-generated by PhantomMindAI incremental learning.',
      '> Review and edit as needed.',
      '',
    ];

    const namingPatterns = this.state.patterns.filter(p => p.type === 'naming' && p.confidence > 0.5);
    if (namingPatterns.length > 0) {
      lines.push('## Naming Conventions', '');
      for (const p of namingPatterns) {
        lines.push(`- ${p.pattern} (confidence: ${(p.confidence * 100).toFixed(0)}%, seen ${p.occurrences} times)`);
      }
      lines.push('');
    }

    const importP = this.state.patterns.filter(p => p.type === 'import' && p.confidence > 0.5);
    if (importP.length > 0) {
      lines.push('## Import Patterns', '');
      for (const p of importP) {
        lines.push(`- ${p.pattern}`);
      }
      lines.push('');
    }

    const structureP = this.state.patterns.filter(p => p.type === 'structure' && p.confidence > 0.5);
    if (structureP.length > 0) {
      lines.push('## Architecture Patterns', '');
      for (const p of structureP) {
        lines.push(`- ${p.pattern}`);
        for (const ex of p.examples) {
          lines.push(`  - e.g., \`${ex}\``);
        }
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Reset all learned patterns
   */
  async reset(): Promise<void> {
    this.state = { patterns: [], fileHistory: [], lastScanTimestamp: '' };
    await this.save();
  }

  private detectNamingPatterns(content: string, ext: string, patterns: Map<string, number>): void {
    // Detect class naming patterns
    const classNames = content.match(/(?:class|interface|type|struct|enum)\s+([A-Z][a-zA-Z0-9]*)/g) ?? [];
    for (const match of classNames) {
      const name = match.split(/\s+/)[1];
      if (name.endsWith('Service')) this.incr(patterns, 'Classes ending with "Service" suffix');
      if (name.endsWith('Controller')) this.incr(patterns, 'Classes ending with "Controller" suffix');
      if (name.endsWith('Repository')) this.incr(patterns, 'Classes ending with "Repository" suffix');
      if (name.endsWith('ViewModel')) this.incr(patterns, 'Classes ending with "ViewModel" suffix');
      if (name.endsWith('UseCase')) this.incr(patterns, 'Classes ending with "UseCase" suffix');
      if (name.endsWith('Handler')) this.incr(patterns, 'Classes ending with "Handler" suffix');
      if (name.endsWith('Manager')) this.incr(patterns, 'Classes ending with "Manager" suffix');
      if (name.endsWith('Provider')) this.incr(patterns, 'Classes ending with "Provider" suffix');
      if (name.startsWith('I') && name[1]?.match(/[A-Z]/)) this.incr(patterns, 'Interfaces use "I" prefix (IService)');
    }

    // Detect function naming
    if (content.match(/async\s+function\s+[a-z]/g)?.length) {
      this.incr(patterns, 'Functions use camelCase naming');
    }

    // Detect constants
    if (content.match(/const\s+[A-Z_]+\s*=/g)?.length) {
      this.incr(patterns, 'Constants use UPPER_SNAKE_CASE');
    }
  }

  private detectImportPatterns(content: string, ext: string, patterns: Map<string, number>): void {
    if (ext === '.ts' || ext === '.tsx' || ext === '.js' || ext === '.jsx') {
      if (content.includes("from 'node:")) this.incr(patterns, 'Use node: protocol for Node.js built-in imports');
      if (content.match(/import type/g)?.length) this.incr(patterns, 'Use type-only imports (import type {})');
      if (content.match(/import \* as/g)?.length) this.incr(patterns, 'Use namespace imports (import * as)');
    }
  }

  private detectStructurePatterns(file: string, patterns: Map<string, string[]>): void {
    const parts = file.split('/');
    if (parts.length >= 2) {
      const dirName = parts[parts.length - 2];
      const fileName = basename(file, extname(file));

      // Detect co-located patterns
      if (fileName.endsWith('.test') || fileName.endsWith('.spec')) {
        this.addToList(patterns, 'Tests co-located with source files', file);
      }

      // Detect feature-based structure
      const featureDirs = ['features', 'modules', 'domains', 'pages', 'routes'];
      if (featureDirs.includes(parts[0] || '')) {
        this.addToList(patterns, `Feature-based directory structure (/${parts[0]}/)`, file);
      }

      // Detect layer-based structure
      const layerDirs = ['models', 'services', 'controllers', 'views', 'utils', 'helpers'];
      if (layerDirs.includes(dirName)) {
        this.addToList(patterns, `Layer-based directory structure (/${dirName}/)`, file);
      }
    }
  }

  private mergePatterns(newPatterns: LearnedPattern[]): void {
    for (const np of newPatterns) {
      const existing = this.state.patterns.find(p => p.pattern === np.pattern && p.type === np.type);
      if (existing) {
        existing.confidence = Math.max(existing.confidence, np.confidence);
        existing.occurrences = Math.max(existing.occurrences, np.occurrences);
        existing.lastSeen = np.lastSeen;
      } else {
        this.state.patterns.push(np);
      }
    }
  }

  private incr(map: Map<string, number>, key: string): void {
    map.set(key, (map.get(key) ?? 0) + 1);
  }

  private addToList(map: Map<string, string[]>, key: string, value: string): void {
    const list = map.get(key) ?? [];
    list.push(value);
    map.set(key, list);
  }

  private async save(): Promise<void> {
    try {
      await mkdir(join(this.projectRoot, '.phantomind', 'memory'), { recursive: true });
      await writeFile(this.statePath, JSON.stringify(this.state, null, 2), 'utf-8');
    } catch {
      // Non-critical
    }
  }
}
