/**
 * PhantomindAI — Base Adapter
 */

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { AdapterName, SyncResult, PhantomConfig } from '../types.js';

export abstract class BaseAdapter {
  abstract readonly name: AdapterName;
  abstract readonly outputPath: string;
  abstract readonly format: 'markdown' | 'json' | 'yaml' | 'text';

  /**
   * Generate instruction file content from context
   */
  abstract generate(skills: string, rules: string, schema: string): string;

  /**
   * Sync context to the adapter's output file
   */
  async sync(
    projectRoot: string,
    config: PhantomConfig,
    dryRun = false,
  ): Promise<SyncResult> {
    try {
      const skills = await this.safeRead(join(projectRoot, config.context.skills));
      const rules = await this.safeRead(join(projectRoot, config.context.rules));
      const schema = await this.safeRead(join(projectRoot, config.context.schema));

      const content = this.generate(skills, rules, schema);
      const outputPath = join(projectRoot, this.outputPath);

      let existingContent = '';
      let fileExists = false;
      try {
        existingContent = await readFile(outputPath, 'utf-8');
        fileExists = true;
      } catch {
        // file doesn't exist yet
      }

      const changed = content !== existingContent;
      const diff = changed ? this.computeDiff(existingContent, content) : undefined;

      if (!dryRun && changed) {
        const { writeFile: wf, mkdir } = await import('node:fs/promises');
        const { dirname } = await import('node:path');
        await mkdir(dirname(outputPath), { recursive: true });
        await wf(outputPath, content, 'utf-8');
      }

      return {
        adapter: this.name,
        outputPath: this.outputPath,
        success: true,
        created: !fileExists && changed,
        changed,
        diff,
      };
    } catch (error) {
      return {
        adapter: this.name,
        outputPath: this.outputPath,
        success: false,
        created: false,
        changed: false,
        error: (error as Error).message,
      };
    }
  }

  protected safeRead(path: string): Promise<string> {
    return readFile(path, 'utf-8').catch(() => '');
  }

  protected wrapHeader(content: string): string {
    return [
      '# ─── AUTO-GENERATED BY PHANTOMIND ─────────────────────────────',
      '# Do not edit this file directly. Edit .phantomind/ source files.',
      `# Last synced: ${new Date().toISOString()}`,
      '# ──────────────────────────────────────────────────────────────',
      '',
      content,
    ].join('\n');
  }

  private computeDiff(oldContent: string, newContent: string): string {
    const oldLines = oldContent.split('\n');
    const newLines = newContent.split('\n');
    const diff: string[] = [];

    const maxLen = Math.max(oldLines.length, newLines.length);
    for (let i = 0; i < maxLen; i++) {
      if (oldLines[i] !== newLines[i]) {
        if (oldLines[i]) diff.push(`- ${oldLines[i]}`);
        if (newLines[i]) diff.push(`+ ${newLines[i]}`);
      }
    }

    return diff.join('\n');
  }
}
